# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faf932194292e0dfb827b53f5793c3a9fac8d45375e9c38dffdc5b080641689d5ad54688f8a5d8513bcc8eace7aeb8536c153e189a4d5bc8b8f11a9f96ad65f5

test:
  secret_key_base: b96015c5248cecece77d06ccd7e4cf5e6f0adc553ffab8f5c29181e817008682dde59714c4fc13426a02de60ff07ca6f68094285e8288b0015175fb31dc3aaba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
